import React from 'react';

const SECTIONS = [
  ['Information We Collect', 'We collect information you provide directly (name, email, phone, shipping addresses) and information generated by your use of the site (orders, browsing activity, device information).'],
  ['How We Use Your Information', 'We use your information to process orders, provide customer support, personalize your shopping experience, and send order-related notifications. We do not sell your personal data to third parties.'],
  ['Payment Information', 'Payments are processed securely through Razorpay. We do not store your card details on our servers.'],
  ['Cookies', 'We use cookies to keep you signed in, remember your cart, and understand how our site is used so we can improve it.'],
  ['Data Sharing', 'We share data only with service providers necessary to fulfill orders (payment processors, delivery partners) under strict confidentiality agreements.'],
  ['Your Rights', 'You can access, update, or delete your account information at any time from My Account, or by contacting our support team.'],
  ['Changes to This Policy', 'We may update this policy periodically. Continued use of the site after changes constitutes acceptance of the revised policy.'],
];

export default function Privacy() {
  return (
    <div className="container-app py-14">
      <div className="mx-auto max-w-3xl">
        <h1 className="section-title">Privacy Policy</h1>
        <p className="mt-2 text-sm text-slate-400">Last updated: January 2026</p>
        <div className="mt-8 space-y-6">
          {SECTIONS.map(([title, body]) => (
            <div key={title}>
              <h2 className="font-semibold text-lg text-slate-800">{title}</h2>
              <p className="mt-1 text-slate-600 leading-relaxed">{body}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
