import React, { useEffect, useState } from 'react';
import { Api } from '../api/client';

const DEFAULT_UPDATED = 'January 2026';

// Fallback sections used until the content loads (or if none were ever set from admin).
const DEFAULT_SECTIONS = [
  { title: 'Information We Collect', body: 'We collect information you provide directly (name, email, phone, shipping addresses) and information generated by your use of the site (orders, browsing activity, device information).' },
  { title: 'How We Use Your Information', body: 'We use your information to process orders, provide customer support, personalize your shopping experience, and send order-related notifications. We do not sell your personal data to third parties.' },
  { title: 'Payment Information', body: 'Payments are processed securely through Razorpay. We do not store your card details on our servers.' },
  { title: 'Cookies', body: 'We use cookies to keep you signed in, remember your cart, and understand how our site is used so we can improve it.' },
  { title: 'Data Sharing', body: 'We share data only with service providers necessary to fulfill orders (payment processors, delivery partners) under strict confidentiality agreements.' },
  { title: 'Your Rights', body: 'You can access, update, or delete your account information at any time from My Account, or by contacting our support team.' },
  { title: 'Changes to This Policy', body: 'We may update this policy periodically. Continued use of the site after changes constitutes acceptance of the revised policy.' },
];

export default function Privacy() {
  const [updated, setUpdated] = useState(DEFAULT_UPDATED);
  const [sections, setSections] = useState(DEFAULT_SECTIONS);

  useEffect(() => {
    Api.siteContent()
      .then(({ content }) => {
        if (content?.privacy_updated) setUpdated(content.privacy_updated);
        if (content?.privacy_sections) {
          try {
            const parsed = JSON.parse(content.privacy_sections);
            if (Array.isArray(parsed) && parsed.length) setSections(parsed);
          } catch { /* keep defaults if JSON is malformed */ }
        }
      })
      .catch(() => {});
  }, []);

  return (
    <div className="container-app py-14">
      <div className="mx-auto max-w-3xl">
        <h1 className="section-title">Privacy Policy</h1>
        <p className="mt-2 text-sm text-slate-400">Last updated: {updated}</p>
        <div className="mt-8 space-y-6">
          {sections.map((s, i) => (
            <div key={i}>
              <h2 className="font-semibold text-lg text-slate-800">{s.title}</h2>
              <p className="mt-1 text-slate-600 leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
