import React, { useEffect, useState } from 'react';
import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css';
import { AdminApi } from '../../api/client';

// Toolbar for the Hero Title editor — lets the admin select part of the
// text (e.g. just the word "Shop") and change its size and color.
const heroTitleModules = {
  toolbar: [
    [{ size: ['small', false, 'large', 'huge'] }],
    ['bold', 'italic'],
    [{ color: [] }],
    ['clean'],
  ],
};

// Same fallback text the public Help Center / Privacy / Terms pages use —
// duplicated here so the admin form isn't blank the first time it's opened.
const DEFAULT_HELP_FAQS = [
  { q: 'How do I track my order?', a: 'Go to My Orders and click on any order to see its live tracking timeline, from placement to delivery.' },
  { q: 'What payment methods do you accept?', a: 'We accept all major cards, UPI, and net banking via Razorpay, as well as Cash on Delivery for eligible orders.' },
  { q: 'How do I cancel an order?', a: 'Orders can be cancelled from the order details page as long as they haven\'t been shipped yet.' },
  { q: 'How do I use a coupon code?', a: 'Enter your coupon code in the "Coupon code" field at checkout and click Apply — the discount will reflect in your order summary.' },
  { q: 'What is your return policy?', a: 'Return eligibility varies by product and is listed on the product page. Most items can be returned within 7–15 days of delivery in original condition.' },
  { q: 'How do I reset my password?', a: 'Click "Forgot password?" on the sign-in page, enter your email, and follow the reset instructions sent to you.' },
];
const DEFAULT_PRIVACY_SECTIONS = [
  { title: 'Information We Collect', body: 'We collect information you provide directly (name, email, phone, shipping addresses) and information generated by your use of the site (orders, browsing activity, device information).' },
  { title: 'How We Use Your Information', body: 'We use your information to process orders, provide customer support, personalize your shopping experience, and send order-related notifications. We do not sell your personal data to third parties.' },
  { title: 'Payment Information', body: 'Payments are processed securely through Razorpay. We do not store your card details on our servers.' },
  { title: 'Cookies', body: 'We use cookies to keep you signed in, remember your cart, and understand how our site is used so we can improve it.' },
  { title: 'Data Sharing', body: 'We share data only with service providers necessary to fulfill orders (payment processors, delivery partners) under strict confidentiality agreements.' },
  { title: 'Your Rights', body: 'You can access, update, or delete your account information at any time from My Account, or by contacting our support team.' },
  { title: 'Changes to This Policy', body: 'We may update this policy periodically. Continued use of the site after changes constitutes acceptance of the revised policy.' },
];
const DEFAULT_TERMS_SECTIONS = [
  { title: 'Acceptance of Terms', body: 'By accessing or using Dostivox, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, please do not use the site.' },
  { title: 'Account Registration', body: 'You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account.' },
  { title: 'Orders & Pricing', body: 'All prices are listed in INR and are subject to change without notice. We reserve the right to refuse or cancel any order due to pricing errors, stock unavailability, or suspected fraud.' },
  { title: 'Payments', body: 'Payments are processed via Razorpay for online payments, or collected in cash for Cash on Delivery orders. By placing an order, you authorize us to charge the selected payment method for the order total.' },
  { title: 'Shipping & Delivery', body: 'Delivery timelines are estimates and may vary based on location and carrier delays. Risk of loss transfers to you upon delivery.' },
  { title: 'Returns & Cancellations', body: 'Orders can be cancelled before they are shipped from My Orders. Return eligibility varies by product category and is detailed on each product page.' },
  { title: 'Intellectual Property', body: 'All content on this site — including logos, product photography, and text — is the property of Dostivox or its licensors and may not be reproduced without permission.' },
  { title: 'Limitation of Liability', body: 'Dostivox is not liable for indirect, incidental, or consequential damages arising from use of the site or products purchased through it, to the maximum extent permitted by law.' },
  { title: 'Governing Law', body: 'These terms are governed by the laws of India, without regard to conflict of law principles.' },
];

function parseJsonArray(str, fallback) {
  if (!str) return fallback;
  try {
    const parsed = JSON.parse(str);
    return Array.isArray(parsed) && parsed.length ? parsed : fallback;
  } catch {
    return fallback;
  }
}

export default function AdminSettings() {
  const [settings, setSettings] = useState({});
  const [saved, setSaved] = useState(false);
  const [contentSaved, setContentSaved] = useState(false);
  const [pagesSaved, setPagesSaved] = useState(false);

  const [helpFaqs, setHelpFaqs] = useState(DEFAULT_HELP_FAQS);
  const [privacySections, setPrivacySections] = useState(DEFAULT_PRIVACY_SECTIONS);
  const [termsSections, setTermsSections] = useState(DEFAULT_TERMS_SECTIONS);

  useEffect(() => {
    AdminApi.settings().then((r) => {
      setSettings(r.settings);
      setHelpFaqs(parseJsonArray(r.settings.help_faqs, DEFAULT_HELP_FAQS));
      setPrivacySections(parseJsonArray(r.settings.privacy_sections, DEFAULT_PRIVACY_SECTIONS));
      setTermsSections(parseJsonArray(r.settings.terms_sections, DEFAULT_TERMS_SECTIONS));
    });
  }, []);

  const field = (key) => settings[key] || '';
  const update = (key) => (e) => setSettings((s) => ({ ...s, [key]: e.target.value }));

  const submit = async (e) => {
    e.preventDefault();
    const { settings: updated } = await AdminApi.updateSettings(settings);
    setSettings(updated);
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  const submitContent = async (e) => {
    e.preventDefault();
    const contentKeys = [
      'home_hero_badge', 'home_hero_title', 'home_hero_subtitle',
      'home_hero_bg_from', 'home_hero_bg_to', 'home_hero_image',
      'home_promo_title', 'home_promo_text', 'home_trending_title',
      'about_heading', 'about_para1', 'about_para2',
      'about_stat1_num', 'about_stat1_label',
      'about_stat2_num', 'about_stat2_label',
      'about_stat3_num', 'about_stat3_label',
    ];
    const payload = Object.fromEntries(contentKeys.map((k) => [k, settings[k] || '']));
    const { settings: updated } = await AdminApi.updateSettings(payload);
    setSettings(updated);
    setContentSaved(true);
    setTimeout(() => setContentSaved(false), 2000);
  };

  // ---- Contact / Help / Legal pages ----
  const updateHelpFaq = (i, key, value) => setHelpFaqs((rows) => rows.map((r, idx) => (idx === i ? { ...r, [key]: value } : r)));
  const addHelpFaq = () => setHelpFaqs((rows) => [...rows, { q: '', a: '' }]);
  const removeHelpFaq = (i) => setHelpFaqs((rows) => rows.filter((_, idx) => idx !== i));

  const updateSection = (setter) => (i, key, value) => setter((rows) => rows.map((r, idx) => (idx === i ? { ...r, [key]: value } : r)));
  const addSection = (setter) => () => setter((rows) => [...rows, { title: '', body: '' }]);
  const removeSection = (setter) => (i) => setter((rows) => rows.filter((_, idx) => idx !== i));

  const submitPages = async (e) => {
    e.preventDefault();
    const payload = {
      contact_heading: settings.contact_heading || '',
      contact_subtitle: settings.contact_subtitle || '',
      contact_email: settings.contact_email || '',
      contact_phone: settings.contact_phone || '',
      contact_hours: settings.contact_hours || '',
      contact_address: settings.contact_address || '',
      help_heading: settings.help_heading || '',
      help_subtitle: settings.help_subtitle || '',
      help_faqs: JSON.stringify(helpFaqs.filter((f) => f.q.trim() && f.a.trim())),
      privacy_updated: settings.privacy_updated || '',
      privacy_sections: JSON.stringify(privacySections.filter((s) => s.title.trim() && s.body.trim())),
      terms_updated: settings.terms_updated || '',
      terms_sections: JSON.stringify(termsSections.filter((s) => s.title.trim() && s.body.trim())),
    };
    const { settings: updated } = await AdminApi.updateSettings(payload);
    setSettings(updated);
    setPagesSaved(true);
    setTimeout(() => setPagesSaved(false), 2000);
  };

  return (
    <div>
      <h1 className="section-title mb-6">Store Settings</h1>
      <form onSubmit={submit} className="card max-w-lg space-y-4 p-6">
        <div>
          <label className="label">Store Name</label>
          <input className="input" value={settings.store_name || ''} onChange={(e) => setSettings((s) => ({ ...s, store_name: e.target.value }))} />
        </div>
        <div>
          <label className="label">Standard Shipping Fee (₹)</label>
          <input type="number" className="input" value={settings.shipping_fee || ''} onChange={(e) => setSettings((s) => ({ ...s, shipping_fee: e.target.value }))} />
        </div>
        <div>
          <label className="label">Free Shipping Above (₹)</label>
          <input type="number" className="input" value={settings.free_shipping_above || ''} onChange={(e) => setSettings((s) => ({ ...s, free_shipping_above: e.target.value }))} />
        </div>
        <div className="flex items-center gap-3">
          <button className="btn-primary">Save Settings</button>
          {saved && <span className="text-sm text-green-600">Saved!</span>}
        </div>
      </form>

      {/* ---------------- WEBSITE CONTENT (Home / About text) ---------------- */}
      <form onSubmit={submitContent} className="card mt-6 max-w-lg space-y-4 p-6">
        <h2 className="font-semibold">Website Content — Home Page</h2>

        <div>
          <label className="label">Hero Badge (small pill text)</label>
          <input className="input" value={field('home_hero_badge')} onChange={update('home_hero_badge')} />
        </div>
        <div>
          <label className="label">Hero Title (select a word, then use the toolbar to resize / color it — e.g. make "Shop" big, "Live Beautifully" small)</label>
          <ReactQuill
            theme="snow"
            modules={heroTitleModules}
            value={field('home_hero_title')}
            onChange={(html) => setSettings((s) => ({ ...s, home_hero_title: html }))}
          />
        </div>
        <div>
          <label className="label">Hero Subtitle</label>
          <textarea className="input" rows={2} value={field('home_hero_subtitle')} onChange={update('home_hero_subtitle')} />
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="label">Background Color (top-left)</label>
            <input type="color" className="input h-10 p-1" value={field('home_hero_bg_from') || '#2c31ab'} onChange={update('home_hero_bg_from')} />
          </div>
          <div>
            <label className="label">Background Color (bottom-right)</label>
            <input type="color" className="input h-10 p-1" value={field('home_hero_bg_to') || '#4a5cf0'} onChange={update('home_hero_bg_to')} />
          </div>
        </div>
        <div>
          <label className="label">Hero Image (paste an image URL)</label>
          <input className="input" value={field('home_hero_image')} onChange={update('home_hero_image')} placeholder="https://..." />
          {field('home_hero_image') && (
            <img src={field('home_hero_image')} alt="Hero preview" className="mt-2 h-32 w-full rounded-lg object-cover" />
          )}
        </div>
        <div>
          <label className="label">Promo Banner Title</label>
          <input className="input" value={field('home_promo_title')} onChange={update('home_promo_title')} />
        </div>
        <div>
          <label className="label">Promo Banner Text</label>
          <textarea className="input" rows={2} value={field('home_promo_text')} onChange={update('home_promo_text')} />
        </div>
<div>
  <label className="label">Trending Section Title</label>
  <input className="input" value={field('home_trending_title')} onChange={update('home_trending_title')} />
</div>
        <h2 className="pt-2 font-semibold">Website Content — About Page</h2>

        <div>
          <label className="label">About Heading</label>
          <input className="input" value={field('about_heading')} onChange={update('about_heading')} />
        </div>
        <div>
          <label className="label">About Paragraph 1</label>
          <textarea className="input" rows={3} value={field('about_para1')} onChange={update('about_para1')} />
        </div>
        <div>
          <label className="label">About Paragraph 2</label>
          <textarea className="input" rows={3} value={field('about_para2')} onChange={update('about_para2')} />
        </div>

        <div className="grid grid-cols-3 gap-3">
          <div>
            <label className="label">Stat 1 Number</label>
            <input className="input" value={field('about_stat1_num')} onChange={update('about_stat1_num')} />
          </div>
          <div>
            <label className="label">Stat 2 Number</label>
            <input className="input" value={field('about_stat2_num')} onChange={update('about_stat2_num')} />
          </div>
          <div>
            <label className="label">Stat 3 Number</label>
            <input className="input" value={field('about_stat3_num')} onChange={update('about_stat3_num')} />
          </div>
          <div>
            <label className="label">Stat 1 Label</label>
            <input className="input" value={field('about_stat1_label')} onChange={update('about_stat1_label')} />
          </div>
          <div>
            <label className="label">Stat 2 Label</label>
            <input className="input" value={field('about_stat2_label')} onChange={update('about_stat2_label')} />
          </div>
          <div>
            <label className="label">Stat 3 Label</label>
            <input className="input" value={field('about_stat3_label')} onChange={update('about_stat3_label')} />
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button className="btn-primary">Save Website Content</button>
          {contentSaved && <span className="text-sm text-green-600">Saved!</span>}
        </div>
      </form>

      {/* ---------------- CONTACT / HELP CENTER / PRIVACY / TERMS ---------------- */}
      <form onSubmit={submitPages} className="card mt-6 max-w-2xl space-y-4 p-6">
        <h2 className="font-semibold">Contact, Help &amp; Legal Pages</h2>

        <div className="rounded-lg border border-slate-200 p-4">
          <h3 className="mb-3 text-sm font-semibold text-slate-700">Contact Page</h3>
          <div className="space-y-3">
            <div>
              <label className="label">Heading</label>
              <input className="input" value={field('contact_heading')} onChange={update('contact_heading')} placeholder="Get in Touch" />
            </div>
            <div>
              <label className="label">Subtitle</label>
              <input className="input" value={field('contact_subtitle')} onChange={update('contact_subtitle')} placeholder="Have a question about an order or product? We'd love to help." />
            </div>
            <div className="grid gap-3 sm:grid-cols-2">
              <div>
                <label className="label">Email</label>
                <input className="input" value={field('contact_email')} onChange={update('contact_email')} placeholder="support@yourdomain.com" />
              </div>
              <div>
                <label className="label">Phone</label>
                <input className="input" value={field('contact_phone')} onChange={update('contact_phone')} placeholder="+91 98765 43210" />
              </div>
              <div>
                <label className="label">Support Hours</label>
                <input className="input" value={field('contact_hours')} onChange={update('contact_hours')} placeholder="Mon–Sat, 9:00 AM – 7:00 PM IST" />
              </div>
              <div>
                <label className="label">Address</label>
                <input className="input" value={field('contact_address')} onChange={update('contact_address')} placeholder="Company address" />
              </div>
            </div>
          </div>
        </div>

        <div className="rounded-lg border border-slate-200 p-4">
          <h3 className="mb-3 text-sm font-semibold text-slate-700">Help Center</h3>
          <div className="grid gap-3 sm:grid-cols-2">
            <div>
              <label className="label">Heading</label>
              <input className="input" value={field('help_heading')} onChange={update('help_heading')} placeholder="Help Center" />
            </div>
            <div>
              <label className="label">Subtitle</label>
              <input className="input" value={field('help_subtitle')} onChange={update('help_subtitle')} placeholder="Answers to the most common questions." />
            </div>
          </div>
          <label className="label mt-3">FAQs</label>
          <div className="space-y-3">
            {helpFaqs.map((f, i) => (
              <div key={i} className="grid gap-2 rounded-lg border border-slate-200 p-3 sm:grid-cols-[1fr_1fr_auto]">
                <input placeholder="Question" className="input" value={f.q} onChange={(e) => updateHelpFaq(i, 'q', e.target.value)} />
                <textarea placeholder="Answer" rows={2} className="input" value={f.a} onChange={(e) => updateHelpFaq(i, 'a', e.target.value)} />
                <button type="button" onClick={() => removeHelpFaq(i)} className="text-sm text-red-500 hover:underline sm:self-start">Remove</button>
              </div>
            ))}
          </div>
          <button type="button" onClick={addHelpFaq} className="btn-ghost mt-2 text-sm">+ Add FAQ</button>
        </div>

        <div className="rounded-lg border border-slate-200 p-4">
          <h3 className="mb-3 text-sm font-semibold text-slate-700">Privacy Policy</h3>
          <div>
            <label className="label">Last Updated (shown on the page)</label>
            <input className="input" value={field('privacy_updated')} onChange={update('privacy_updated')} placeholder="January 2026" />
          </div>
          <label className="label mt-3">Sections</label>
          <div className="space-y-3">
            {privacySections.map((s, i) => (
              <div key={i} className="rounded-lg border border-slate-200 p-3">
                <input placeholder="Section Title" className="input mb-2" value={s.title} onChange={(e) => updateSection(setPrivacySections)(i, 'title', e.target.value)} />
                <textarea placeholder="Section Body" rows={3} className="input" value={s.body} onChange={(e) => updateSection(setPrivacySections)(i, 'body', e.target.value)} />
                <button type="button" onClick={() => removeSection(setPrivacySections)(i)} className="mt-2 text-sm text-red-500 hover:underline">Remove</button>
              </div>
            ))}
          </div>
          <button type="button" onClick={addSection(setPrivacySections)} className="btn-ghost mt-2 text-sm">+ Add Section</button>
        </div>

        <div className="rounded-lg border border-slate-200 p-4">
          <h3 className="mb-3 text-sm font-semibold text-slate-700">Terms of Service</h3>
          <div>
            <label className="label">Last Updated (shown on the page)</label>
            <input className="input" value={field('terms_updated')} onChange={update('terms_updated')} placeholder="January 2026" />
          </div>
          <label className="label mt-3">Sections</label>
          <div className="space-y-3">
            {termsSections.map((s, i) => (
              <div key={i} className="rounded-lg border border-slate-200 p-3">
                <input placeholder="Section Title" className="input mb-2" value={s.title} onChange={(e) => updateSection(setTermsSections)(i, 'title', e.target.value)} />
                <textarea placeholder="Section Body" rows={3} className="input" value={s.body} onChange={(e) => updateSection(setTermsSections)(i, 'body', e.target.value)} />
                <button type="button" onClick={() => removeSection(setTermsSections)(i)} className="mt-2 text-sm text-red-500 hover:underline">Remove</button>
              </div>
            ))}
          </div>
          <button type="button" onClick={addSection(setTermsSections)} className="btn-ghost mt-2 text-sm">+ Add Section</button>
        </div>

        <div className="flex items-center gap-3">
          <button className="btn-primary">Save Contact, Help &amp; Legal Pages</button>
          {pagesSaved && <span className="text-sm text-green-600">Saved!</span>}
        </div>
      </form>

      <div className="card mt-6 max-w-lg p-6">
        <h2 className="mb-2 font-semibold">Payment Gateway</h2>
        <p className="text-sm text-slate-500">Razorpay keys are configured via the backend <code>.env</code> file (<code>RAZORPAY_KEY_ID</code> / <code>RAZORPAY_KEY_SECRET</code>) and are not editable from this panel for security reasons.</p>
      </div>
    </div>
  );
}
